Add User Repository
Morphclue/code-camp-2 pull request #47
Opened 2022-06-08 09:42 UTC by SteffenKr

Implemented User Repository mentioned in #40 similiar to the implementation of #46

2022-06-08 09:47 UTC, wasanderes94 approved these changes

2022-06-08 15:17 UTC, Morphclue requested changes

2022-06-12 14:00 UTC, SteffenKr commented on app/src/main/java/org/feature/fox/coffee_counter/ui/HistoryView.kt
>  package org.feature.fox.coffee_counter.ui
did the merge and changed the User Repository to use the bearere token

2022-06-12 14:03 UTC, Morphclue approved these changes

2022-06-12 14:07 UTC, merged